spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: rinoimob-backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rinoimob}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.rinoimob: DEBUG
    
server:
  port: ${SERVER_PORT:39000}
