package com.rinoimob.domain.dto;

public record TenantWebsiteConfigResponse(
        String companyName,
        String logoUrl,
        String faviconUrl,
        String primaryColor,
        String secondaryColor,
        String description,
        String heroTitle,
        String heroSubtitle,
        String phone,
        String email,
        String address,
        String instagramUrl,
        String whatsappNumber,
        String facebookUrl,
        String heroImageUrl,
        String featuredSectionTitle,
        String featuredSectionSubtitle,
        String launchesSectionTitle,
        String launchesSectionSubtitle,
        String categoriesSectionTitle,
        String categoriesSectionSubtitle,
        String servicesSectionTitle,
        String servicesSectionSubtitle,
        String servicesFormTitle,
        String servicesFormSubtitle,
        String statsSectionTitle,
        String statsSectionSubtitle,
        String blogSectionTitle,
        String blogSectionSubtitle,
        String ctaSectionTitle,
        String ctaSectionSubtitle,
        String customDomain
) {
}
